# APP NAME
spring.application.name=planpaz

# DATABASE (POSTGRESQL)
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/planpaz}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:admin}

# JPA CONFIG
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT TOKEN SECRET
api.security.token.secret=${JWT_SECRET:jmjpcatmplc}
logging.level.org.springframework.security=DEBUG

# WEATHER API KEY
weather.api.key=${WEATHER_API_KEY:fae921abdc310d74d9685c5c542b0fad}

# GEOAPIFY
geoapify.base-url=${GEOAPIFY_BASE_URL:https://api.geoapify.com/v1}
geoapify.api.key=${GEOAPIFY_API_KEY:645d3457a5b245ae93f695e72448f2e8}

# MAIL CONFIGURATION (Corrigido: sem espaços na senha do app do Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:ofchumanin@gmail.com}
spring.mail.password=${MAIL_PASSWORD:iuzkcxcvqicezzog}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# APP URL
app.base-url=${APP_BASE_URL:https://debunk-quail-revert.ngrok-free.dev}
server.address=0.0.0.0

# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:hvrq4r5h}
cloudinary.api-key=${CLOUDINARY_API_KEY:993546125894756}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:4GIipsOQLvy9JsWLWH01qxJ681E}

# Multipart upload limit config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB