spring.application.name=planpaz

spring.datasource.url=jdbc:postgresql://localhost:5432/planpaz
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret="jmjpcatmplc"
weather.api.key=fae921abdc310d74d9685c5c542b0fad

geoapify.base-url=https://api.geoapify.com/v1
geoapify.api.key=645d3457a5b245ae93f695e72448f2e8

logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ofchumanin@gmail.com
spring.mail.password=iuzk cxcv qice zzog
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#para testar no ngrok: app.base-url=https://debunk-quail-revert.ngrok-free.dev
#para testar no app: ip do seu pc + porta. app.base-url=http://192.168.18.67:8080
# goma: app.base-url=http://192.168.18.67:8080
# vo: app.base-url=http://192.168.0.18:8080
app.base-url=https://debunk-quail-revert.ngrok-free.dev
server.address=0.0.0.0


# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:hvrq4r5h}
cloudinary.api-key=${CLOUDINARY_API_KEY:993546125894756}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:4GIipsOQLvy9JsWLWH01qxJ681E}

# Multipart upload limit config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB