spring.application.name=planpaz

spring.datasource.url=jdbc:postgresql://localhost:5432/planpaz
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret="jmjpcatmplc"
weather.api.key=fae921abdc310d74d9685c5c542b0fad
logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ofchumanin@gmail.com
spring.mail.password=stebfcwrkompcxyp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
