-- Limpeza das tabelas
DELETE FROM public.garden_plant;
DELETE FROM public.plant_stage;
DELETE FROM public.plant;

-- Inserção do catálogo completo de plantas
INSERT INTO public.plant (
    id, name, scientific_name, description, watering_level, luminosity_level, temperature_level, size, type, image
) VALUES 
(gen_random_uuid(), 'Jibóia', 'Epipremnum aureum', 'Planta ornamental de fácil cultivo e folhagem marcante.', 'WEEKLY', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'OTHER', 'https://cdn.awsli.com.br/800x800/1539/1539472/produto/213557807/epipremnum-aureum-golden-pothos-6-n0nexjqvn6.jpg'),
(gen_random_uuid(), 'Manjericão', 'Ocimum basilicum', 'Erva aromática muito utilizada na culinária.', 'DAILY', 'INTENSE', 'HIGH', 'SMALL', 'AROMATIC', 'https://cdn.awsli.com.br/600x700/416/416989/produto/129418172/manjeric-o-knz7c4z77f.jpg'),
(gen_random_uuid(), 'Orégano', 'Origanum vulgare', 'Erva aromática resistente e tempero clássico.', 'SPORADIC', 'INTENSE', 'MEDIUM', 'SMALL', 'AROMATIC', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfvNljI7o1Px_urceR7OUWDKu7qkVOUqlAN3o9dm_Gpw&s=10'),
(gen_random_uuid(), 'Orquídea (Phalaenopsis)', 'Phalaenopsis spp.', 'Planta ornamental delicada com belas flores.', 'WEEKLY', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'OTHER', 'https://images.tcdn.com.br/img/img_prod/487611/doce_phalaenopsis_pink_146_2_20230109105256.jpg'),
(gen_random_uuid(), 'Mini Coroa de Cristo', 'Euphorbia milii var. splendens', 'Planta ornamental espinhosa e bastante resistente.', 'SPORADIC', 'INTENSE', 'HIGH', 'SMALL', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIRrET1jHh-qU8WSyILqI19lWbsmOp8956TVOPajUWZg&s=10'),
(gen_random_uuid(), 'Cacto Coroa de Frade', 'Melocactus zehntneri', 'Cacto ornamental nativo de regiões quentes e secas.', 'SPORADIC', 'INTENSE', 'HIGH', 'SMALL', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR33QD4UvfZNL_oxQxOtdtPeOflFxROrxNytaIpN9bc7A&s'),
(gen_random_uuid(), 'Alface', 'Lactuca sativa', 'Hortaliça comestível de crescimento rápido.', 'DAILY', 'INTENSE', 'LOW', 'SMALL', 'EDIBLE', 'https://lh3.googleusercontent.com/gg-dl/AAQ_wbF2DeZKlBoSnTHF6zdrpR1VMDA2rBWfLL7h6KjGe1tJG39xCaHENArGCFsR90fePAPgVA6i0x4Iie6jvzfJuOp6INSP1PSMI6o8zlsw-FAwOvFophzvQ1OsWcI3J1u8pkNksrUuFfDS8uOxssIOD9pvhUfSIFev0HQjlXQkvLz8njB8Xw=s1024-rj'),
(gen_random_uuid(), 'Hortelã', 'Mentha spicata', 'Erva aromática excelente para chás e temperos.', 'DAILY', 'INTENSE', 'MEDIUM', 'SMALL', 'AROMATIC', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJaHNvWMNIQAjyPBaJTJddRhFJszRJdkbbuB4wVEEZAQ&s=10'),
(gen_random_uuid(), 'Cebolinha', 'Allium fistulosum', 'Temperos e folhas comestíveis muito populares.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'EDIBLE', 'https://cdn.awsli.com.br/800x800/416/416989/produto/391891843/cebolinha-2-jmdxiurgbp.jpg'),
(gen_random_uuid(), 'Tomilho', 'Thymus vulgaris', 'Erva aromática de porte baixo e sabor marcante.', 'SPORADIC', 'INTENSE', 'MEDIUM', 'SMALL', 'AROMATIC', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvMD1jKCN3x2XuCDfYWiyVKrmmWwjyBVGvT266yM3fUQ&s=10'),
(gen_random_uuid(), 'Couve', 'Brassica oleracea var. acephala', 'Hortaliça nutritiva de folhas comestíveis.', 'DAILY', 'INTENSE', 'MEDIUM', 'MEDIUM', 'EDIBLE', 'https://www.picturethisai.com/image-handle/website_cmsname/image/1080/222010746480820224.jpeg?x-oss-process=image/format,webp/resize,s_500&v=1.0'),
(gen_random_uuid(), 'Coentro', 'Coriandrum sativum', 'Erva e tempero de sabor característico.', 'DAILY', 'INTENSE', 'MEDIUM', 'SMALL', 'EDIBLE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0kjPGSs_Vmpcoeo7zSBCy1jK2WQpg47OzrxdsF2pOE5jnAbF6_hx5lNyU&s=10'),
(gen_random_uuid(), 'Jade', 'Crassula ovata', 'Suculenta ornamental de folhas resistentes.', 'SPORADIC', 'INTENSE', 'HIGH', 'MEDIUM', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJWXY35hk09zLbA50cX1Li7JbQUZf8LdtwQqQZQhimfg&s=10'),
(gen_random_uuid(), 'Violeta', 'Saintpaulia ionantha', 'Planta ornamental delicada de vasos internos.', 'WEEKLY', 'MEDIUM', 'MEDIUM', 'SMALL', 'OTHER', 'https://www.langdonsflowers.com/cdn/shop/products/shutterstock_35049577_2000x_a37a4fe1-e238-4015-b8e2-7fe3db137708.jpg?v=1661178288'),
(gen_random_uuid(), 'Colar de Pérolas', 'Senecio rowleyanus', 'Suculenta pendente muito apreciada.', 'SPORADIC', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF50tEUkooIfRUxKRL8DWsR3dv-UTnJTVIjuxwKgURmw&s=10'),
(gen_random_uuid(), 'Samambaia', 'Nephrolepis exaltata', 'Planta ornamental de folhagem volumosa.', 'DAILY', 'MEDIUM', 'MEDIUM', 'LARGE', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEGf2iJWSVF85FMt48_qyP5EK5tGy0Y2JbvBMPM6IhnQ&s=10'),
(gen_random_uuid(), 'Espada de São Jorge', 'Dracaena trifasciata', 'Planta ornamental extremamente resistente.', 'SPORADIC', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'OTHER', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTrMAo7P2odHeQoQlOe7pWKtjXjAszu7YFoqXbYntn9A&s=10'),
(gen_random_uuid(), 'Tomate Cereja', 'Solanum lycopersicum var. cerasiforme', 'Planta frutífera comestível de porte médio.', 'DAILY', 'INTENSE', 'HIGH', 'MEDIUM', 'EDIBLE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTP_lMV3HJERJdPkHx0PikqtIbM_RSmHWlZ0PmvkPdIUg&s=10'),
(gen_random_uuid(), 'Rabanete', 'Raphanus sativus', 'Raiz comestível de ciclo muito rápido.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'EDIBLE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmnNbIva3vqf0YHKjIcCQ5Cu4atmJ9hp3mY1I3h50d1w&s'),
(gen_random_uuid(), 'Salsinha', 'Petroselinum crispum', 'Erva aromática indispensável na cozinha.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'AROMATIC', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtP2VWIk9QEu1CeDI2JWSsCe-B4O7BRaRK6eITtGInBQ&s=10'),
(gen_random_uuid(), 'Erva Cidreira', 'Melissa officinalis', 'Erva calmante usada principalmente para chás.', 'WEEKLY', 'MEDIUM', 'MEDIUM', 'MEDIUM', 'AROMATIC', 'https://images.tcdn.com.br/img/img_prod/799330/sementes_de_erva_cidreira_melissa_linha_cheff_3025_1_ae9955547151ad0d55f6a4b4eb95b5a2.jpg'),
(gen_random_uuid(), 'Ora-pro-nóbis', 'Pereskia aculeata', 'Planta alimentícia não convencional (PANC) muito nutritiva.', 'WEEKLY', 'INTENSE', 'HIGH', 'LARGE', 'EDIBLE', 'https://s2.glbimg.com/b071-m6rYLXsNqLjPwh1VKTeZBs=/620x455/e.glbimg.com/og/ed/f/original/2021/09/09/pereskia_aculeata_mill.jpg'),
(gen_random_uuid(), 'Pimenta Biquinho', 'Capsicum chinense', 'Pimenta comestível saborosa e sem ardência.', 'DAILY', 'INTENSE', 'HIGH', 'MEDIUM', 'EDIBLE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKCZv_3w-iBxJ51aemu1LCrkpcbo7ftM6Di1yaQ_0ZPA&s=10'),
(gen_random_uuid(), 'Babosa', 'Aloe vera', 'Planta ornamental e medicinal muito conhecida.', 'SPORADIC', 'INTENSE', 'HIGH', 'MEDIUM', 'OTHER', 'https://images.tcdn.com.br/img/img_prod/1105580/babosa_aloe_vera_179_variacao_59_1_ca555c191aafb2fdff5454dd33c48f66.jpg'),
(gen_random_uuid(), 'Morango', 'Fragaria x ananassa', 'Planta frutífera comestível pequena.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'EDIBLE', 'https://www.thjardins.com.br/wp-content/uploads/2026/07/fragaria-x-ananassa-fragissimo-92532384.jpg'),
(gen_random_uuid(), 'Erva-doce', 'Foeniculum vulgare', 'Erva aromática com aroma e sabor de anís.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'MEDIUM', 'AROMATIC', 'https://florayamamura.com.br/wp-content/uploads/2024/06/Erva-Doce.jpg'),
(gen_random_uuid(), 'Alecrim', 'Salvia rosmarinus', 'Erva aromática muito resistente e perfumada.', 'SPORADIC', 'INTENSE', 'HIGH', 'MEDIUM', 'AROMATIC', 'https://mondiniplantas.cdn.magazord.com.br/img/2026/04/produto/7854/alecrim-adulta.jpg?ims=800x800'),
(gen_random_uuid(), 'Camomila', 'Matricaria chamomilla', 'Erva medicinal usada em infusões.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'AROMATIC', 'https://www.shutterstock.com/image-photo/medicinal-chamomile-matricaria-recutita-chamomilla-260nw-2640781971.jpg'),
(gen_random_uuid(), 'Rúcula', 'Eruca vesicaria', 'Hortaliça comestível de sabor levemente picante.', 'WEEKLY', 'INTENSE', 'MEDIUM', 'SMALL', 'EDIBLE', 'https://www.infoescola.com/wp-content/uploads/2010/09/r%C3%BAcula_760063117.jpg'),
(gen_random_uuid(), 'Almeirão Amarelo', 'Cichorium intybus', 'Hortaliça comestível de folhas levemente amargas.', 'DAILY', 'INTENSE', 'MEDIUM', 'MEDIUM', 'EDIBLE', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbpBePCAiFhBANv04cqUJEK1_1Kx-PNLjurer8ggOHa1zy8Mx442QDAb8&s=10');